### ISSUE TITLE
Component layout proposal for landscape view / high res

### ISSUE THREAD

**Issue by kamelie1706** [benchmarko/CPCBasicTS#1]
Hi,

Fantastic project!
Any hope to get a layout more suitable to landscape/high res screen such as this 
 
![Screenshot 2023-10-12 162121](https://github.com/benchmarko/CPCBasicTS/assets/58597593/dbc974d9-43fd-4e23-998c-58dba8a0eab7)

Ideally would be we could move the different components as we wish ... It is a long time I have not dealt with HTML but was under impression could be done in HTML5
https://www.w3schools.com/howto/howto_js_draggable.asp

**Comment by benchmarko** [comment]
Good idea!
The virtual keyboard is already movable... ;)
I was also thinking about different views for coding and game play.

**Comment by kamelie1706** [comment]
Indeed realized it after! I could not move it on the side to the output screen only up and down but I guess this is just how it is coded now in html layout

**Comment by benchmarko** [comment]
I experimented a bit with moving the components, now it's close to your suggestion (index2.html):
https://benchmarko.github.io/CPCBasicTS/index2.html?showKbd=true&showVariable=true
![cpcbasicts_layout2](https://github.com/benchmarko/CPCBasicTS/assets/48618353/03adf0a0-ee9e-4b9a-a0bd-e9d93b950df7)

Could still be improved, e.g. the keyboard is a bit too wide.
On narrow screens (or mobiles), the right area is attached at the bottom. Now with additional functions in between, not so optimal.

I'm thinking about putting the CPC screen on the left. And replacing the open/collapse buttons with settings buttons.

**Comment by kamelie1706** [comment]
Looks great!

**Comment by benchmarko** [comment]
After some UI changes you can now drag elements (v0.2.6). This needs to be activated under "View".
