### ISSUE TITLE
Option to restrict to Basic 1.0 & Speed to original

### ISSUE THREAD

**Issue by kamelie1706** [benchmarko/CPCBasicTS#2]
Hi

I using that for development so would be great if I could restrict it to Basic 1.0 for max compatibility.
I saw also the "speed" setting but could not figure out how to set it up to match the original 464 speed .... 
 
Thx!

**Comment by benchmarko** [comment]
Good idea to select the Basic version. I need to think about it. Maybe just reducing the instruction set and the number of arguments for some instructions. There are also some subtile differences when using DRAW...

The speed selector is just an experiment. Currently it modifies the delay until the next bunch of code is simulated. Not sure if it would be possible to have something like accurate timing as it is used for Z80 emulators...

**Comment by kamelie1706** [comment]
Understand this is not an emulator 
Close enough would be already great ... does not need "perfect" ;-)

**Comment by benchmarko** [comment]
You can now set the BASIC version under "Settings". When set to "1.0", programs using BASIC 1.1 instructions won't compile any more (version 0.1.8).

**Comment by kamelie1706** [comment]
> You can now set the BASIC version under "Settings". When set to "1.0", programs using BASIC 1.1 instructions won't compile any more (version 0.1.8).
Great it even includes the ugly 1.0 bug :-)
?DEC$((0,"#")
