### ISSUE TITLE
Text mode view from CPCBasic

### ISSUE THREAD

**Issue by kamelie1706** [benchmarko/CPCBasicTS#3]
Hi

Might have missed it but the Text Mode from CPCBasic seems missing .... very useful function I seem to be missing and go back specifically to CPCBasic.

Best tool so far to develop Basic Amstrad!

**Comment by benchmarko** [comment]
A few weeks ago I improved the Text Mode. You can now also select characters with a mouse click. Use the Canvas selector in the Settings menu to activate Text Mode. I hope you do not need graphical canvas and text mode at the same time.
I'm glad to hear that you enjoy using CPCBasic!

**Comment by kamelie1706** [comment]
Totally missed that!
It is perfectly ok that way.
Thx
